### ISSUE TITLE
长字段怎么折行展示

### ISSUE THREAD

**Issue by 452896915** [abodelot/jquery.json-viewer#16]
长字段怎么折行展示，能实现自动折行么

**Comment by abodelot** [comment]
Can you please describe your issue in English? Thanks!

**Comment by edokan** [comment]
`max-width` and `.json-viewer` are just sample.

```css
pre.json-viewer {
    max-width: 200px;
    white-space: normal;
}
```
