### ISSUE TITLE
suggestion for json filter 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [abodelot/jquery.json-viewer#19]
Hello @jason-lynch 

There are perfect plugin for json object viewer so good
but sometimes the json is so large 
so there are idea for filter text and manage by collapse so here or part of object only show 

This is only my suggestion 

Thank you

**Comment by edokan** [comment]
A quick and dirty workaround. `width` is just for demo

```css
.json-string {
    max-width: 50px;
    text-overflow: ellipsis;
    display: inline-block;
    overflow-x: hidden;
}
```

on demo page it looks like this

![image](https://user-images.githubusercontent.com/1482410/102221412-26242000-3eb0-11eb-8930-333269006516.png)

1. it may be a better solution to use `::before` and `::after` to create double quotes, so it would just clip the text portion and still show double quotes like `"123.."` instead of `"123..`

2. Text is selectable and can be copied, but needs some button to view full text. 

3. Clipped may need some tooltip to quickly glance over.
