### ISSUE TITLE
How to limit the maximum height of json-viewer

### ISSUE THREAD

**Issue by nomadlx** [abodelot/jquery.json-viewer#25]
I want it to be displayed in a div with a fixed length and width, and with a scroll wheel if more than that. What should I do?

**Comment by abodelot** [comment]
Hi, you can use the following CSS properties on the element used for the rendering.

```css
pre#json-renderer {
  overflow: auto;
  height: 300px;
  width: 300px;
}
```
